### ISSUE TITLE
Dynamic Rotation Trick

### ISSUE THREAD

**Issue by ArvinArora** [francesco-mannella/Echo-State-Networks#1]
Hi Francesco,

I tried to find a source (reasearch paper or else) for the dynamic rotation trick but have not been successful - do have any hints regarding theoretical foundations or empirical evidence?

Kind Regards
Arvin

**Comment by francesco-mannella** [comment]
Ciao Arvin.
Infortunatelly at the moment there is no pubblication. We are still working
on the principle so to formalize it and prove it as an optimization tool. I
just mentioned it in the appendix of my paper
Selection of cortical dynamics for motor behaviour by the basal ganglia.
Mannella F, et al. Biol Cybern.

2015.https://link.springer.com/article/10.1007%2Fs00422-015-0662-6

Cheers,
Francesco

Il 4 feb 2018 14:04, "ArvinArora" <notifications@github.com> ha scritto:
